name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3.2.1
    
    - name: qmake ../src
      run: |
        mkdir build && cd build
        qmake ../src
    - name: make
      run: |
        cd build
        make -j4
#        make -j4 && make clean

    - name: make check
      run: make check
